# /.tmuxinator.yml
name: gen-indices
root: /development/rust_proj

startup_window: gen-indices

windows:
  - gen-indices:
      layout: 3ccd,274x63,0,0{90x63,0,0,47,90x63,91,0,49,92x63,182,0[92x22,182,0,50,92x21,182,23,51,92x18,182,45,52]}
      root: /development/rust_proj/gen-indices
      panes:
        - cargo:
            - cargo check
            - coolprompt
        - note:
            - git status -sb
            - coolprompt
        - coolprompt
        - coolprompt
        - coolprompt
  - tests:
      layout: 3ccd,274x63,0,0{90x63,0,0,47,90x63,91,0,49,92x63,182,0[92x22,182,0,50,92x21,182,23,51,92x18,182,45,52]}
      root: /development/rust_proj/peekaboo
      panes:
        - coolprompt
        - coolprompt
        - coolprompt
        - coolprompt
        - coolprompt
